#!/bin/bash
PHP_VERSION="${1}"

if [[ ${1} =~ ([0-9]+\.[0-9]+)\.[0-9]+ ]]; then
  PHP_SHORT_VERSION=${BASH_REMATCH[1]}
else
  echo "Wrong version number given"
  exit 1
fi

PHPBREW_PATH="/root/.phpbrew/"
PHPBREW_PHP_PATH="${PHPBREW_PATH}php/php-${1}/"

#+openssl-- --enable-wddx
phpbrew -d install ${PHP_VERSION} +brewme +dbs -- --enable-fpm --with-fpm-user=root --with-fpm-group=root --with-gd=shared --enable-gd-native-ttf --with-jpeg-dir=/usr --with-png-dir=/usr
source /root/.phpbrew/bashrc
phpbrew -d switch php-${PHP_VERSION}

phpbrew -d ext install +brewme -- --with-gd=shared --enable-gd-native-ttf --with-jpeg-dir=/usr --with-png-dir=/usr

# Load version specific extensions
if [[ ${PHP_SHORT_VERSION} == '5.3' || $PHP_SHORT_VERSION == '5.4' ]]; then
  phpbrew -d ext install apc 3.1.13
  phpbrew -d ext install xdebug 2.2.5
fi

if [[ ${PHP_SHORT_VERSION} == '5.5' || $PHP_SHORT_VERSION == '5.6' ]]; then
  phpbrew -d ext install opcache stable
  phpbrew -d ext install apcu 4.0.7
fi

phpbrew clean ${PHP_VERSION}
rm -R /root/.phpbrew/build/php-${PHP_VERSION}
rm -R /root/.phpbrew/distfiles
rm -R /root/.phpbrew/tmp

phpbrew off
